import { Generator } from './Generator';

class DishGenerator extends Generator {

	/**
	 * Generates a dish.
	 * @param {String} separator A character to insert between words.
	 * @param {Boolean} verbose Set to true for longer results.
	 * @returns {String} A dish.
	 */
	generate( separator, verbose ) {

		const adjectives = [
			'baked',
			'barbecued',
			'boiled',
			'braised',
			'cooked',
			'crunchy',
			'delicious',
			'double',
			'dried',
			'fermented',
			'fragrant',
			'fresh',
			'fried',
			'giant',
			'grilled',
			'marinated',
			'microwaved',
			'mini',
			'poached',
			'premium',
			'raw',
			'roasted',
			'salted',
			'smoked',
			'sour',
			'spicy',
			'steamed',
			'stuffed',
			'sweet',
			'tasty',
			'warm',
			'yummy',
		];

		const condiments = [
			'aioli',
			'basil',
			'bolognese',
			'caramel',
			'carbonara',
			'chili',
			'cilantro',
			'cinnamon',
			'coleslaw',
			'cream',
			'curry',
			'garlic',
			'ginger',
			'gravy',
			'guacamole',
			'harissa',
			'honey',
			'ketchup',
			'mayonnaise',
			'mint',
			'miso',
			'mustard',
			'oregano',
			'pepper',
			'piment',
			'sesame',
			'tabasco',
			'tartar',
			'vanilla',
			'vinegar',
			'yakitori',
			'wasabi',
		];

		const ingredients = [
			'almond',
			'apple',
			'artichoke',
			'asparagus',
			'avocado',
			'bacon',
			'banana',
			'bean',
			'blueberry',
			'beef',
			'broccoli',
			'cabbage',
			'carrot',
			'cashew',
			'catfish',
			'cauliflower',
			'celery',
			'cheddar',
			'cherry',
			'chickpea',
			'chicken',
			'chocolate',
			'chorizo',
			'coconut',
			'cod',
			'coppa',
			'corn',
			'crab',
			'cucumber',
			'deer',
			'duck',
			'eggplant',
			'egg',
			'fish',
			'fig',
			'gouda',
			'grapes',
			'grapefruit',
			'ham',
			'halibut',
			'hazelnut',
			'kale',
			'kimchi',
			'kiwi',
			'lamb',
			'lettuce',
			'lemon',
			'lime',
			'lobster',
			'mandarine',
			'mango',
			'merguez',
			'mussels',
			'mutton',
			'mushroom',
			'mozzarella',
			'olive',
			'onion',
			'orange',
			'oyster',
			'papaya',
			'pastrami',
			'peach',
			'peanut',
			'pear',
			'pecan',
			'pickles',
			'pineapple',
			'pistachio',
			'pepperoni',
			'plum',
			'popcorn',
			'pork',
			'potato',
			'prawn',
			'pumpkin',
			'rabbit',
			'radish',
			'salami',
			'salmon',
			'seabass',
			'shrimp',
			'spinach',
			'strawberry',
			'soy',
			'tangerine',
			'tomato',
			'tofu',
			'turnip',
			'tuna',
			'turkey',
			'veal',
			'venison',
			'walnut',
			'watermelon',
			'zucchini',
		];

		const dishes = [
			'bagel',
			'ball',
			'bar',
			'biscuit',
			'bread',
			'brownie',
			'bubblegum',
			'bun',
			'burger',
			'butter',
			'cake',
			'candy',
			'cannelloni',
			'carpaccio',
			'casserole',
			'cereal',
			'chili',
			'chip',
			'chutney',
			'cocktail',
			'cookie',
			'cracker',
			'croissant',
			'croquette',
			'cupcake',
			'dip',
			'donut',
			'farfalle',
			'filet',
			'fondue',
			'fries',
			'gazpacho',
			'gnocchi',
			'gravy',
			'hotdog',
			'infusion',
			'jam',
			'jello',
			'jelly',
			'jerky',
			'juice',
			'kebab',
			'lasagna',
			'linguine',
			'loaf',
			'macaroni',
			'maki',
			'mash',
			'meatballs',
			'milkshake',
			'milk',
			'mousse',
			'muffin',
			'nachos',
			'noodles',
			'nuggets',
			'omelet',
			'oil',
			'pancake',
			'pasta',
			'penne',
			'pesto',
			'pie',
			'pizza',
			'porridge',
			'pretzel',
			'pudding',
			'puff',
			'quesadilla',
			'quiche',
			'ramen',
			'roll',
			'rice',
			'ravioli',
			'salad',
			'sandwich',
			'salsa',
			'samosa',
			'sauce',
			'sausage',
			'scone',
			'shake',
			'sherbet',
			'smoothie',
			'soup',
			'spaghetti',
			'steak',
			'stew',
			'sticks',
			'sushi',
			'tagliatelle',
			'tart',
			'toast',
			'tortilla',
			'yogurt',
			'waffle',
		];

		const combos = ( verbose ) ? [
			[ adjectives, condiments, ingredients ],
			[ adjectives, condiments, dishes ],
			[ adjectives, ingredients, dishes ],
			[ condiments, ingredients, dishes ],
			[ ingredients, ingredients, dishes ],
			[ adjectives, condiments, ingredients, dishes ],
			[ adjectives, ingredients, ingredients, dishes ],
			[ condiments, ingredients, ingredients, dishes ],
		] : [
			[ adjectives, condiments ],
			[ adjectives, dishes ],
			[ adjectives, ingredients ],
			[ condiments, dishes ],
			[ ingredients, condiments ],
			[ ingredients, dishes ],
			[ ingredients, ingredients ],
		];

		return this.random.item( combos )
			.map( ( component ) => this.random.item( component ) )
			.join( separator );

	}

}



export { DishGenerator };
